name: strava_analytics
version: '1.0.0'
config-version: 2

profile: strava_analytics

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +on_schema_change: "sync_all_columns"
  strava_analytics:
    staging:
      +schema: silver_layer
      +materialized: table
    marts:
      +schema: gold_layer
      +materialized: view
