strava_analytics:
    target: development
    outputs:
      development:
        type: bigquery
        method: oauth
        project: strava-dashboard-487415
        dataset: default_dataset
        location: europe-west3
        threads: 1
        timeout_seconds: 300