strava_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: strava-dashboard-487415
      dataset: strava_dev
      keyfile: ../strava-dashboard-487415-2dde21217ace.json
      location: EU
      threads: 1
      timeout_seconds: 300
