from google.cloud.bigquery import SchemaField

ACTIVITIES_SCHEMA = [                                                                                                                                                             
      SchemaField("id",                           "INTEGER",   "NULLABLE"),
      SchemaField("resource_state",               "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("name",                         "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("type",                         "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("sport_type",                   "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("workout_type",                 "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("device_name",                  "STRING",    "NULLABLE"),
      SchemaField("external_id",                  "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("upload_id",                    "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("upload_id_str",                "STRING",    "NULLABLE"),
      SchemaField("gear_id",                      "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("visibility",                   "STRING",    "NULLABLE"),
      SchemaField("timezone",                     "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("utc_offset",                   "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("start_date",                   "TIMESTAMP", "NULLABLE"),
      SchemaField("start_date_local",             "TIMESTAMP", "NULLABLE"),                                                                                                         
      SchemaField("distance",                     "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("moving_time",                  "INTEGER",   "NULLABLE"),
      SchemaField("elapsed_time",                 "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("total_elevation_gain",         "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("elev_high",                    "FLOAT",     "NULLABLE"),
      SchemaField("elev_low",                     "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("average_speed",                "FLOAT",     "NULLABLE"),
      SchemaField("max_speed",                    "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("average_cadence",              "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("average_temp",                 "INTEGER",   "NULLABLE"),
      SchemaField("average_watts",                "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("kilojoules",                   "FLOAT",     "NULLABLE"),
      SchemaField("device_watts",                 "BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("has_heartrate",                "BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("average_heartrate",            "FLOAT",     "NULLABLE"),
      SchemaField("max_heartrate",                "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("heartrate_opt_out",            "BOOLEAN",   "NULLABLE"),
      SchemaField("display_hide_heartrate_option","BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("suffer_score",                 "FLOAT",     "NULLABLE"),                                                                                                         
      SchemaField("achievement_count",            "INTEGER",   "NULLABLE"),
      SchemaField("kudos_count",                  "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("comment_count",                "INTEGER",   "NULLABLE"),
      SchemaField("athlete_count",                "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("photo_count",                  "INTEGER",   "NULLABLE"),
      SchemaField("total_photo_count",            "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("pr_count",                     "INTEGER",   "NULLABLE"),                                                                                                         
      SchemaField("trainer",                      "BOOLEAN",   "NULLABLE"),
      SchemaField("commute",                      "BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("manual",                       "BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("private",                      "BOOLEAN",   "NULLABLE"),
      SchemaField("flagged",                      "BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("from_accepted_tag",            "BOOLEAN",   "NULLABLE"),                                                                                                         
      SchemaField("has_kudoed",                   "BOOLEAN",   "NULLABLE"),
      SchemaField("location_city",                "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("location_state",               "STRING",    "NULLABLE"),
      SchemaField("location_country",             "STRING",    "NULLABLE"),                                                                                                         
      SchemaField("start_latlng",                 "FLOAT",     "REPEATED"),                                                                                                         
      SchemaField("end_latlng",                   "FLOAT",     "REPEATED"),
      SchemaField("athlete", "RECORD", "NULLABLE", fields=[                                                                                                                         
          SchemaField("id",             "INTEGER", "NULLABLE"),
          SchemaField("resource_state", "INTEGER", "NULLABLE"),                                                                                                                     
      ]),         
      SchemaField("map", "RECORD", "NULLABLE", fields=[                                                                                                                             
          SchemaField("id",               "STRING",  "NULLABLE"),                                                                                                                   
          SchemaField("summary_polyline", "STRING",  "NULLABLE"),
          SchemaField("resource_state",   "INTEGER", "NULLABLE"),                                                                                                                   
      ]),                                                                                                                                                                           
  ]